# Generated by Django 3.1.3 on 2020-12-07 03:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookappointment',
            name='booked_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 6, 19, 43, 4, 128219), null=True),
        ),
    ]
